### ISSUE TITLE
Add cli to create task hooks

### ISSUE THREAD

**Issue by ethanfrey** [Lay3rLabs/avs-toolkit#102]
Follow up from #77 

Add cli subcommand to add task hooks to a task queue contract.
Also add some docs how to do that.

**Comment by ismellike** [comment]
The current setup adds a hook to the sender's address.

If we want to make the cli useful, then I think we'll need:
- Optional `hook_admin` in Config. None => hooks disabled
   - Only the hook admin will be allowed to add/remove hooks
- New parameter for adding a hook to a specific address: `hook_address`

**Comment by ethanfrey** [comment]
Those suggestions sounds good to me.

I would leave it to @ismellike and @NoahSaso to work out the needs here and make it useful for the demos Noah is building.

The main goal here is to make something to support product's demos in DevCon, so they are the boss in this case.

**Comment by ethanfrey** [comment]
closed via https://github.com/Lay3rLabs/avs-toolkit/pull/112
