### ISSUE TITLE
consider adding generic commands to CLI

### ISSUE THREAD

**Issue by dakom** [Lay3rLabs/avs-toolkit#33]
see https://github.com/Lay3rLabs/avs-toolkit/pull/28#discussion_r1780913605 for a bit of context.

basically, the climb repo has some minimal but useful commands like "generate wallet", "show balance", etc. in an example CLI project (it also has that in an example frontend project)

currently, the avs-toolkit does not have all these commands, and so if you want a "batteries included" tool, you're kinda stuck jumping between projects.

one solution would be to just add those commands into the avs-toolkit CLI, so it has everything, but that isn't on the current sprint roadmap and there isn't a definitive decision as of now, so opening this issue to track it

**Comment by ethanfrey** [comment]
Cool. Go for copy-paste for now.
Unless there is an easy way for avs-verifier to import subcommands from climb?
That would actually be the biggest win. To keep the code in climb and import the commands we want. Not sure if possible, but I can dream...

If that would take more than an hour or so, cut-and-paste is fine for now

**Comment by dakom** [comment]
Sure, I'll give it a shot, basically to make a new climb package that isn't part of the core but rather a `cli-base` or something like that. It'll probably make a few assumptions like `tracing` and take in a `ChainConfig` and `Signer`, but it'll have all the generic basic subcommands available.

Will timebox it to like an hour and if it's too messy I'll cut bait and go for cut-and-paste

**Comment by dakom** [comment]
opened https://github.com/Lay3rLabs/climb/issues/13 to track the changes to climb as a separate issue from using those changes here

**Comment by dakom** [comment]
@ethanfrey just a heads up, I made a lot of progress, imho it's looking good, I expect to finish this when I'm back this afternoon but gotta run for now
