### ISSUE TITLE
Merge command to deploy contracts and service

### ISSUE THREAD

**Issue by ismellike** [Lay3rLabs/avs-toolkit#89]
Post-hackathon request by Jake:
![image](https://github.com/user-attachments/assets/d5a65b93-5979-4a4d-86bf-e4f3c37da92b)

**Comment by JakeHartnell** [comment]
This is low priority, but could be nice if possible.

**Comment by gangov** [comment]
unnasigned, as this isn't recommended as per the Google Doc

**Comment by ethanfrey** [comment]
Let's not do this. the wasmartic stuff is a temporary hack that won't be available to avs deployers later.
The contract setup will be.
